services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: het-parket-gilde-web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./data:/var/www/html/data
    env_file:
      - .env
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - APP_DEBUG=${APP_DEBUG}
    restart: unless-stopped
    networks:
      - parket-network

networks:
  parket-network:
    driver: bridge
